stages:
    - compile
    - test
    - deploy

compile_job:
    stage: compile
    script:
        - mvn compile

test_job:
    stage: test
    script:
        - mvn test

deploy_job:
    stage: deploy
    script:
        - export PORT=5000
        - dpl --provider=heroku --app=wacc09-simplewebapp --api-key=5d02f58e-554b-4443-b9f9-3d96071eafb3
